# Generated by Django 4.2.15 on 2024-08-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_author_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
