# Generated by Django 3.2.19 on 2024-08-29 06:07

import dish.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=dish.models.dish_image_file_path)),
                ('category', models.CharField(max_length=500)),
            ],
        ),
    ]
