# Generated by Django 3.2.19 on 2024-08-29 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_auto_20240829_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='category_id',
            new_name='category',
        ),
    ]
