# Generated by Django 4.2.15 on 2024-08-20 05:43

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=1000, null=True)),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=400, null=True)),
                ('cost', models.IntegerField(null=True)),
                ('rating', models.FloatField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('time', models.TimeField(default=django.utils.timezone.now, null=True)),
                ('current_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
