# Generated by Django 4.2.15 on 2024-08-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('degree', models.CharField(max_length=20)),
                ('certification', models.TextField()),
                ('full_name', models.CharField(editable=False, max_length=100)),
            ],
        ),
    ]
