# Generated by Django 4.2.15 on 2024-08-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product_name',
            new_name='BikeName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cost',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_time',
            new_name='Current_time',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
