# Generated by Django 4.2.15 on 2024-08-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_product_name_user_bikename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Cost',
        ),
    ]
